[project]
name = "lightshot-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4==4.13.3",
    "lxml==5.3.1",
    "mysql-connector-python==9.2.0",
    "requests==2.32.3",
]
