name: Deploying a docker container to ECR

on:
  push:
    branches: [ "main" ]
    
env:
  AWS_REGION: AWS_REGION
  ECR_REPOSITORY: ECR_REPOSITORY                           
  CONTAINER_NAME: MY_CONTAINER_NAME

jobs:
    job_validation:
        runs-on: ubuntu-latest
        environment: production
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region: ${{ env.AWS_REGION }}
          
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1  
          run: echo "the validating proccess has begun"
          run: apt-get install docker aws
          run: docker -v
          run: aws -v 
          run: aws sts get-caller-identity
          
    job_build_push: 
        needs: job_validation
        steps:
          run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
          run: docker build -t lightshot_scraper .
          run: 
