name: Deploying a docker container to ECR

on:
  push:
    branches: [ "main" ]
    
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID}}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}                        
  CONTAINER_NAME: ${{ vars.AWS_REGION }}

jobs:
    job_validation:
        runs-on: ubuntu-latest
        environment: production
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region:  ${{ vars.AWS_REGION }}
          
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1  
        
        - name: Validation
          run: | 
            echo "the validating proccess has begun"
            #apt-get install docker aws
            docker -v
            aws -v 
            aws sts get-caller-identity
          
    job_build_push: 
        runs-on: ubuntu-latest
        needs: job_validation
        steps:
        - name: Pushing the docker container to ECR
          run: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            docker build -t $CONTAINER_NAME .
            docker tag $CONTAINER_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest
