name: TEST
on:
  push:
    branches: [main]
jobs: 
    job_test:
      runs-on: ubuntu-latest
      environment: production
      steps:
      - name: connect to ssh
        run: ssh -i -i <(echo ${{ secrets.EC2_PRIVATE_SSH_KEY }}) ec2-user@${{ secrets.HOST_DNS }}
